name: Copy guideline

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  copy-guideline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy guideline
        run: cp resources/boost/guidelines/core.blade.php .ai/guidelines/copilot-cli.blade.php

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update guideline
          commit_options: '--no-verify'
          file_pattern: '.ai/guidelines/copilot-cli.blade.php'
